// examples/react/src/components/normal.tsx
import React, { createElement, useEffect, useMemo, useState } from 'react'
import { Modal, Button } from 'antd'
import { useOpenModal, useUpdateModal } from '@usemodals/react'

import Lazy1 from './lazy-modals/modal-1'

export default () => {
  const [ state, setState ] = useState({
    visible: true,
    content: 'test111'
  })

  const openModal = useOpenModal()
  const updateModal = useUpdateModal()

  return (
    <div>
      <Button onClick={() => {
        openModal('modal1', {
          title: 'Modal1',
          content: 'I\' init props'
        })
      }} >
        Open Normal Modal
      </Button>
      <Button onClick={() => {
        openModal('modal1', {
          title: 'Modal1',
          content: 'I\' init props'
        })

        setTimeout(() => {
          updateModal('modal1', {
            content: 'I\'m updated props'
          }, true)
        }, 5000)
      }}>
        Open UpdateAble Modal(merge props)
      </Button>
      <Button onClick={() => {
        openModal('modal1', {
          title: 'Modal1',
          content: 'I\' init props'
        })

        setTimeout(() => {
          updateModal('modal1', {
            content: 'I\'m updated props'
          })
        }, 5000)
      }}>
        Open UpdateAble Modal
      </Button>
    </div>
  );
};

// packages/vue/example/normal.vue

<template>
  <div style="margin-top: 30px;">
    <div style="margin-top: 10px;">
      <ElButton @click="openModal('normalModal')">Open NormalModal</ElButton>
    </div>
    <div style="margin-top: 10px;">
      <ElButton @click="() => openAndUpdate()">Open NormalModal and update props after 3s (No Merge)</ElButton>
    </div>
    <div style="margin-top: 10px;">
      <ElButton @click="openAndUpdate(true)">Open NormalModal and update props after 3s (Merge Props)</ElButton>
    </div>
    <NormalModal />
  </div>
</template>

<script>
import NormalModal from './modals/normal-modal.vue'

export default {
  name: 'normal',
  components: {
    NormalModal
  },
  methods: {
    openAndUpdate(merge) {
      this.openModal('normalModal', { content: 'modal init content' })

      setTimeout(() => {
        if (merge) {
          this.updateModal('normalModal', { desc: 'modal updated content', merge }, merge)
          return
        }
        this.updateModal('normalModal', { desc: 'modal updated content' })
      }, 3000)
    }
  }
}
</script>
